version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: crmuser
      POSTGRES_PASSWORD: crmpass
      POSTGRES_DB: crm
    ports:
      - '5432:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: crmuser
      DB_PASSWORD: crmpass
      DB_NAME: crm
    ports:
      - '8080:8080'
    command: go run main.go
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    depends_on:
      - backend
    command: yarn dev --host
  ai-service:
    image: ollama/ollama:latest
    ports:
      - '8000:11434'
    volumes:
      - ollama:/root/.ollama
volumes:
  ollama:
